name: Build Binaries
on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - run: npm install -g pkg
      - run: pkg libcal-cli.js --targets node20-linux-x64,node20-macos-x64,node20-win-x64 --output libcal-cli
      - run: tar -czvf libcal-cli-linux.tar.gz libcal-cli-linux
      - run: tar -czvf libcal-cli-macos.tar.gz libcal-cli-macos

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            libcal-cli-linux.tar.gz
            libcal-cli-macos.tar.gz
            libcal-cli-win.exe
